### ISSUE TITLE
crash 2

### ISSUE THREAD

**Issue by mitchiru** [mitchiru/luther#11]
Our terminal machine cant handle our transitions :-(

can you please provide an easy alternative to be switched in the body:

<body>
<script>transitions = full|easy|none;</script>

full: as it is
easy: fade in and out only
none: just change screen by hide() and show()

**Comment by jiimka** [comment]
sure. I suggest adding it as a body "data-transition" property

**Comment by mitchiru** [comment]
yes. good.

**Comment by jiimka** [comment]
@mitchiru - enabled different animation types for each of our three pages: please refer to "body" tag's "data-transition" property.
