### ISSUE TITLE
Estimate change of playlist.html

### ISSUE THREAD

**Issue by mitchiru** [mitchiru/luther#13]
Could you do this additionally this/next week?

Can you please first estimate, how much time it would be to change playlist.html to following layout:
![bach audioplayer](https://cloud.githubusercontent.com/assets/892231/23911380/ededd21a-08dc-11e7-923f-174b5e1e89dd.jpg)

adding features:
- time controll / slider like http://kolber.github.io/audiojs/
- fix headline and subline up below and above the slider

questions
- is the shadow up and down possible?

it is optimized for ipad

**Comment by jiimka** [comment]
@mitchiru - it doesn't look like there's too much work here. My guesstimate is about half a day of work.
I think the shadow up and down shouldn't be too tricky to add.
