### ISSUE TITLE
Positioning of button

### ISSUE THREAD

**Issue by mitchiru** [mitchiru/luther#2]
The text is not in the right position
![screen shot 2017-03-08 at 09 08 49](https://cloud.githubusercontent.com/assets/892231/23695337/e1e48b6a-03de-11e7-96e5-649f0d42aef6.png)

**Comment by mitchiru** [comment]
here too
![screen shot 2017-03-08 at 09 14 00](https://cloud.githubusercontent.com/assets/892231/23695458/98f86dc6-03df-11e7-8fa0-0d59cc316506.png)

**Comment by jiimka** [comment]
@mitchiru - hope this fix helps.
Please, let me know if the issue still persists.

**Comment by mitchiru** [comment]
no, still too high.

on windows chrome looks good, but on OSX chrome and safari doesn't.

**Comment by jiimka** [comment]
@mitchiru - what about the kioks system that we aim - does it look good there?

**Comment by mitchiru** [comment]
I dont know yet. because we couldnt navigate the mouse on our test system :-)

**Comment by jiimka** [comment]
the only fix I can think of so far is to use different styles for Mac OS
