### ISSUE TITLE
new story bücher

### ISSUE THREAD

**Issue by mitchiru** [mitchiru/luther#24]
This is the new story
https://projects.invisionapp.com/share/U4BC9RVC3#/screens/229480569

Assets are in img/bucher/

1. overview screen with click on year (the graphic with the books is not finished yet)
1516 1517 1518 1519 1520 1521

2. Overview of the year (all books in it)
- all books filtered by the clicked year
- display the thumbnail
- also possibility to change filter

3. Detail from json
(bucher.html)

German: title - subtitle
English: title - title_en (title=german translation)

**Comment by jiimka** [comment]
Good morning :)
It's pretty much close to done (luckily, using JS instead of 100 files).
But please, check if the content is populated as expected, and probably you'll find smth else to fix/improve
