### ISSUE TITLE
Books back

### ISSUE THREAD

**Issue by mitchiru** [mitchiru/luther#28]
IS: When I am at a book detail, and click on overview, I get to the start page

SHOULD: I should get to the books page with the year of the recently browsed book selected

**Comment by jiimka** [comment]
@mitchiru - if I got it right, it should return to the previously selected year overview.
if I got it wrong and it should return to the year overview related to the last viewed book details page, we could just remove the 'flag' param from populateBookDetails() function

**Comment by mitchiru** [comment]
SHOULD: when hit back, It should  return to the overview of the year of the selected book (the books year can change however since we can rotate through all books.)

IS: The first book i am looking at is working when I go back. But when I choose an other year, it keeps going back to that same year.

**Comment by mitchiru** [comment]
it is fixed, i was looking at an old version
