### ISSUE TITLE
missing assets

### ISSUE THREAD

**Issue by jiimka** [mitchiru/luther#5]
Here is the list of images present on InvisionApp preview, but not included to the assets.
catacombs:
https://projects.invisionapp.com/d/main#/console/10315611/222770090/inspect
Das Kolosseum:
https://projects.invisionapp.com/d/main#/console/10315611/222770092/inspect

Also, there is a number of dummy images throughout the pages (about 10 or so, I guess). Will need to revisit it later.

Another thing - related to audio files that you mentioned in Skype: for Wittenberg and Sant’ Agostine.
There is a dummy file for Sant’ Agostine, so I went ahead and added it for now. And Wittenberg has no audio nor in the InvisionApp, nor among the audio dummies, so I've just removed audio from the page

**Comment by mitchiru** [comment]
Please also remove saint agostino mp3 and the audio button on that page. it is an mistake from the client.

**Comment by mitchiru** [comment]
I will get the assets

**Comment by jiimka** [comment]
deleted the saint agostino mp3 and the audio button on that page

**Comment by mitchiru** [comment]
here should be everything:
https://we.tl/yNwWhMim4c

**Comment by jiimka** [comment]
added some missing images.
There are only 3 dummy images left so far (Chur, Findelhaus and Cancelleria):
https://projects.invisionapp.com/d/main#/console/10315611/222141894/preview
https://projects.invisionapp.com/d/main#/console/10315611/222141897/preview
https://projects.invisionapp.com/d/main#/console/10315611/222770088/preview
